# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='values',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='fields',
            field=models.TextField(blank=True),
        ),
    ]
