# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160413_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
