# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20160413_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='fields',
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='initial_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='type',
            field=models.CharField(choices=[('int', 'Integer'), ('date', 'Date'), ('str', 'String'), ('text', 'Text')], default='char', max_length=4),
        ),
    ]
