# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20160419_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemafield',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
