# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20160420_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='values',
        ),
        migrations.AlterField(
            model_name='questionnairevalue',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms.Questionnaire'),
        ),
    ]
