# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20160423_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='is_published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
