# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_schema_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Questionnaire Answer', 'verbose_name_plural': 'Questionnaire Answers'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'verbose_name': 'Questionnaire Schema', 'verbose_name_plural': 'Questionnaire Schemas'},
        ),
    ]
